### ISSUE TITLE
Javascript & Flash port

### ISSUE THREAD

**Issue by HaoliangWang** [jazlab/moog.github.io#1]
Hi, Is there a Javascript & Flash port for MOOG, so that experiments can be run online interactively? Thanks!

**Comment by nwatters01** [comment]
Hi Haoliang,
Currently we do not have a way to run experiments online.  We have considered it, and are thinking about making a Flask server interface or auto-generating a javascript version, but haven't started working on that and aren't sure if/when that will ultimately happen.
Best,
Nick
